### ISSUE TITLE
Issue with cdm_from_con; can't find "visit_detail" table

### ISSUE THREAD

**Issue by ZorzArg** [OdyOSG/CDMConnector#11]
When running **cdm_from_con**, I get the following error:

               _Failed to prepare query: ERROR:  relation "cdm.visit_detail" does not exist_

As "visit_detail" is an optional table in the CDM, I suggest to add a flag in **cdm_from_con**  to include or not include this table (or any other optional tables).

**Comment by ablack3** [comment]
Thanks @ZorzArg. Let's define what "optional" means and make sure we have that right. My understanding is that the visit_detail table is required to exist but is not required to be populated. I'm basing my interpretation off of the spec file here and from various conversations I've had. Let me know if you believe otherwise.

https://github.com/OHDSI/CommonDataModel/blob/main/inst/csv/OMOP_CDMv5.4_Table_Level.csv

<img width="463" alt="image" src="https://user-images.githubusercontent.com/10227522/218189753-378bba32-2f83-4a00-8204-32a819c81f37.png">

**Comment by ablack3** [comment]
You can do something like

`cdm <- cdm_from_con(con, cdm_schema = "cdm", cdm_tables = c(tbl_group("default"), -visit_detail))`

to ignore the visit_detail table.
I agree it should probably be dropped from the default but I'm cautious about changing it because it would be a breaking change.

**Comment by ZorzArg** [comment]
> Thanks @ZorzArg. Let's define what "optional" means and make sure we have that right. My understanding is that the visit_detail table is required to exist but is not required to be populated. I'm basing my interpretation off of the spec file here and from various conversations I've had. Let me know if you believe otherwise.
> 
> https://github.com/OHDSI/CommonDataModel/blob/main/inst/csv/OMOP_CDMv5.4_Table_Level.csv
> 
>


I see what you mean. I got confused with the wording here: https://ohdsi.github.io/CommonDataModel/cdm53.html#VISIT_DETAIL
I guess "optional" means "not necessarily populated".


> You can do something like
> 
> `cdm <- cdm_from_con(con, cdm_schema = "cdm", cdm_tables = c(tbl_group("default"), -visit_detail))`
> 
> to ignore the visit_detail table. I agree it should probably be dropped from the default table group but I'm cautious about changing it because it would be a breaking change.

That's a nice solution. Thanks
